name: MCQuarry
main: com.itzbradmc.mcquarry.MCQuarry
version: '0.1.3'
author: ItzBradMc
description: Tekkit style quarry
api-version: 1.13

commands:
  mq:
    description: main command
  mcquarry:
    description: main command